import json

def normalize(s):
    return s.replace('\u2019',"'").replace('\u2018',"'").replace('\u201c','"').replace('\u201d','"')

COMMON = {
    "Politics": ("政治", ""),
    "Business": ("商业", ""),
    "The weekly cartoon": ("每周漫画", ""),
    "Economic data, commodities and markets": ("经济数据、大宗商品与市场", "指标"),
    "Letters to the editor": ("读者来信", ""),
    "Should Europe's pensions be reformed?": ("欧洲养老金应该改革吗？", ""),
}

ECONOMIST_0404 = {**COMMON,
    "How China hopes to win from the war": ("中国如何希望从这场战争中获益", ""),
    "The perils of a ground war in Iran": ("伊朗地面战争的危险", ""),
    "Lessons for the world from tiny Hungary": ("小国匈牙利给世界的教训", ""),
    "How worried should you be about private credit?": ("私人信贷有多值得担忧？", ""),
    "Index providers should not bend the rules for Elon Musk": ("指数提供商不应为马斯克屈尊破例", ""),
    "The IT department: Where AI goes to die": ("IT部门：AI的埋葬地", ""),
    "Might Hungary's election sweep away MAGA's favourite foreign leader?": ("匈牙利大选能否扫除MAGA最喜爱的外国领导人？", ""),
    "A guide to the private-credit crisis": ("私人信贷危机指南", ""),
    '"Liberation Year" has not freed American factories': (""解放年"并未解放美国工厂", ""),
    "The war with Iran has blown up an America First policy": ("对伊朗的战争炸毁了美国优先政策", ""),
    "Our prediction for how SCOTUS will rule on birthright citizenship": ("我们对最高法院裁决出生公民权的预测", ""),
    "From MAHA to haha": ("从MAHA到笑话", ""),
    "Demand for autism care is soaring. The system is struggling to cope": ("对自闭症护理的需求激增，体系应对吃力", ""),
    "Donald Trump and the art of bad diplomacy": ("唐纳德·特朗普与拙劣外交的艺术", ""),
    "Mark Carney's honeymoon is about to get even better": ("马克·卡尼的蜜月期即将更上一层楼", ""),
    "The Venezuela Donald Trump \"runs\" is a land of surreal contrasts": ("特朗普"管理"的委内瑞拉是一片超现实的对比之地", ""),
    "How the Gulf's war is becoming Asia's crisis too": ("海湾战争如何也成为亚洲的危机", ""),
    "America's foes see opportunity in Asia's oil shock": ("美国的对手在亚洲石油冲击中看到了机遇", ""),
    "Why women, more than men, are abandoning rural Japan": ("为何女性比男性更多地离开日本农村", ""),
    "Is Bollywood's latest megahit propaganda for Narendra Modi?": ("宝莱坞最新大片是莫迪的宣传片吗？", ""),
    "Why the Iran war hurts China less than its rivals": ("为何伊朗战争对中国的伤害小于其竞争对手", ""),
    "Is China covering up a violent attack at a Beijing market?": ("中国是否在掩盖北京一市场的暴力袭击事件？", ""),
    "China's leadership is about to be shaken up": ("中国领导层即将洗牌", ""),
    "For China's officials, the goal was once growth. Now it's loyalty": ("对中国官员而言，目标曾经是增长，如今是忠诚", ""),
    "How would American ground forces take Kharg?": ("美国地面部队将如何夺取哈尔格岛？", ""),
    "Iran has damaged a surprising amount of American kit": ("伊朗损毁了数量惊人的美国军备", ""),
    "The war in Iran is nearing a crossroads": ("伊朗战争正逼近十字路口", ""),
    "Iran's opposition in exile is rethinking its support for the war": ("流亡海外的伊朗反对派正在反思对战争的支持", ""),
    "Iran's permissive party islands contain hidden dangers": ("伊朗宽松的派对岛屿暗藏危机", ""),
    "The Houthis' attack on Israel may point to escalation in the Iran war": ("胡塞武装袭击以色列或预示伊朗战争升级", ""),
    "Binyamin Netanyahu is down—but not out": ("本雅明·内塔尼亚胡落难，但未出局", ""),
    "Senegal's government denies the gravity of its debt crisis": ("塞内加尔政府否认债务危机的严重性", ""),
    "A revolution is coming for Germany's intelligence services": ("德国情报机构即将迎来一场变革", ""),
    "Will the European Union's next member come from the north?": ("欧盟的下一个成员国将来自北方吗？", ""),
    "On the front lines, Russian soldiers pay officers to stay alive": ("在前线，俄罗斯士兵向军官行贿以求活命", ""),
    "A final favour Emmanuel Macron could do for France": ("马克龙能为法国做的最后一件好事", ""),
    "How poor data hobble Britain's immigration policy": ("糟糕的数据如何拖累英国移民政策", ""),
    "Right-wingers want ICE-style mass deportations in Britain": ("右翼人士希望在英国推行ICE式大规模驱逐", ""),
    "Can reforms save the European Convention on Human Rights?": ("改革能拯救欧洲人权公约吗？", ""),
    "Labour needs to slow down its clean-power mission": ("工党需要放慢其清洁能源使命的推进步伐", ""),
    "The British government should not panic over fuel bills": ("英国政府不应为燃料账单恐慌", ""),
    "For the love of sticky toffee pudding": ("对黏糊糊太妃布丁的热爱", ""),
    "The tarts and vicars party": ("果挞与牧师派对", ""),
    "How Africa is changing Catholicism": ("非洲如何正在改变天主教", ""),
    "Hurricane Trump threatens to blow China off course": ("特朗普飓风威胁令中国偏离航道", ""),
    "How the Department of Justice became a feeding ground for MAGA lobbyists": ("司法部如何成为MAGA说客的牧场", ""),
    "The plan to make IPOs great again": ("让IPO再次伟大的计划", ""),
    "India's oil refiners are feeling the squeeze from the Gulf war": ("印度炼油商正感受到海湾战争的挤压", ""),
    "War with Iran could accelerate Africa's oil revival": ("对伊朗的战争可能加速非洲石油复苏", ""),
    "The hidden currency of office life": ("职场生活的隐性货币", ""),
    "How Fox News is luring in Gen Z": ("福克斯新闻如何吸引Z世代", ""),
    "How Iran is making a mint from Donald Trump's war": ("伊朗如何从特朗普的战争中大捞一笔", ""),
    "Coal is back in fashion": ("煤炭重回时尚", ""),
    '"Liberation Day" has reshaped trade—but not as Donald Trump hoped': (""解放日"重塑了贸易——但并非特朗普所期望的方式", ""),
    "After Iran, gold is looking less glittery": ("伊朗战争后，黄金光泽有所减退", ""),
    "Can a country get too rich?": ("一个国家能富到头吗？", ""),
    "Scientists are working on \"everything vaccines\"": ("科学家正在研究"万能疫苗"", ""),
    "A trio of firms want to clean up steelmaking": ("三家公司想要清洁炼钢业", ""),
    "Why a startup is teaching human brain cells to play \"Doom\"": ("为何一家初创公司让人类脑细胞玩《毁灭战士》", ""),
    "Should you track your VO2 max?": ("你应该追踪自己的最大摄氧量吗？", ""),
    "The number of Catholic saints is climbing heavenwards": ("天主教圣人数量扶摇直上", ""),
    "Why Gen Z is taking up boomer hobbies": ("为何Z世代开始追捧婴儿潮一代的爱好", ""),
    "Six books about basketball to read after March Madness": ("三月疯狂过后值得一读的六本篮球书", ""),
    "Is looksmaxxing dangerous or silly?": ("外貌极化是危险还是愚蠢？", ""),
    "Bots are often bad writers. But so are most humans": ("机器人通常是糟糕的写手，但大多数人类也一样", ""),
    "Who is Demis Hassabis, the man behind Google DeepMind?": ("谁是德米斯·哈萨比斯，谷歌DeepMind背后的那个人？", ""),
    "Michel Rolland was the world's first flying winemaker": ("米歇尔·罗兰是世界上第一位飞行酿酒师", ""),
}

ECONOMIST_0328 = {**COMMON,
    "Advantage Iran": ("伊朗占优", ""),
    "Europe should think twice before weakening its merger rules": ("欧洲在削弱并购规则前应三思", ""),
    "The case against energy bail-outs": ("反对能源纾困的理由", ""),
    "Mexico must unleash its private sector": ("墨西哥必须解放私营部门", ""),
    "England has shown the world how to replace farm subsidies": ("英格兰向世界展示了如何替代农业补贴", ""),
    "Europe's choice: Grow, or become a vassal": ("欧洲的选择：增长，还是沦为藩属", ""),
    "Iran's Revolutionary Guards won't defend the regime to the last man": ("伊朗革命卫队不会为政权战至最后一人", ""),
    "Hormuz is not the only weak spot for global trade": ("霍尔木兹并非全球贸易的唯一软肋", ""),
    "What a battle to reopen the Strait of Hormuz would look like": ("重开霍尔木兹海峡的战斗将是什么样子", ""),
    "Marco Rubio, the chameleon in the war room": ("马可·卢比奥，战情室里的变色龙", ""),
    "America's pro-Israel lobby is facing a backlash": ("美国亲以色列游说团体正遭遇强烈反弹", ""),
    "Snarled airports and frozen funding test the new DHS secretary": ("混乱的机场和冻结的资金考验新任国土安全部长", ""),
    "America's spies have a lot to complain about": ("美国情报人员有很多怨言", ""),
    "America goes on cyber-offence": ("美国转入网络进攻模式", ""),
    "Why Donald Trump is putting his face on a coin": ("为何特朗普要把自己的脸印在硬币上", ""),
    "For Donald Trump, Cuba is everything Iran is not": ("对特朗普而言，古巴是伊朗所没有的一切", ""),
    "Industrial liberalism and its critics": ("工业自由主义及其批评者", ""),
    "If 19th-century plutocrats are dinosaurs, we're now in Jurassic Park": ("如果19世纪的财阀是恐龙，我们现在身处侏罗纪公园", ""),
    "Six books to understand the Gilded Age": ("理解镀金时代的六本书", ""),
    "Mexico's broken economy": ("墨西哥破损的经济", ""),
    "Brazil has a secret weapon against oil shocks": ("巴西有一件应对石油冲击的秘密武器", ""),
    "Why the number of Islamic schools in Canada is soaring": ("加拿大伊斯兰学校数量为何激增", ""),
    "The world's most unaffordable housing is not where you think": ("全球最难负担的住房不在你以为的地方", ""),
    "The end of the world's longest-running Maoist insurgency": ("世界上持续时间最长的毛主义武装叛乱的终结", ""),
    "China is breaking into one of the world's weirdest car markets": ("中国正打入全球最奇特的汽车市场之一", ""),
    "How Chinese companies are reshaping Indonesia": ("中国企业如何重塑印度尼西亚", ""),
    "Millions of Burmese struggle to find safety in Thailand": ("数百万缅甸人在泰国艰难求生", ""),
    "Why Bangalore has India's best billionaires": ("班加罗尔为何拥有印度最优质的亿万富翁", ""),
    "Does the Iran war increase the risk of a Chinese attack on Taiwan?": ("伊朗战争是否增加了中国进攻台湾的风险？", ""),
    "Jiang Shengnan is the most vocal woman in Chinese politics": ("江胜男是中国政界最敢言的女性", ""),
    "China's huge pork industry is a victim of its own success": ("中国庞大的猪肉行业成了自身成功的牺牲品", ""),
    "China's government both drives and constrains the rise of AI": ("中国政府既推动又制约AI的崛起", ""),
    "Donald Trump says he is close to a deal with Iran": ("特朗普称与伊朗的协议即将达成", ""),
    "The Revolutionary Guards are taking over Iran": ("革命卫队正在接管伊朗", ""),
    "In the current Gulf war, water may prove as decisive as oil": ("在当前的海湾战争中，水或许将与石油一样具有决定性作用", ""),
    "Iran's regime walls off the internet": ("伊朗政权封锁互联网", ""),
    "Israeli settlers are growing more violent in the West Bank": ("以色列定居者在西岸的暴力行为日益升级", ""),
    "How long will Israel stay in Lebanon?": ("以色列将在黎巴嫩驻留多久？", ""),
    "Botswana prepares to take an even bigger gamble on diamonds": ("博茨瓦纳准备在钻石上下更大的赌注", ""),
    "Russia wants to limit contact with the outside world": ("俄罗斯希望限制与外部世界的接触", ""),
    "Germany's Social Democrats gaze into the abyss": ("德国社会民主党凝视深渊", ""),
    "France offers some hope for defeating populists": ("法国为击败民粹主义者带来一线希望", ""),
    "Giorgia Meloni's big setback in Italy": ("乔治娅·梅洛尼在意大利遭遇重大挫折", ""),
    "Ukraine's top drone commander wants to bleed Russia's army dry": ("乌克兰顶级无人机指挥官要让俄军流尽鲜血", ""),
    "Europe's populist right should be outvoted rather than ostracised": ("欧洲民粹主义右翼应被票数击败，而非被排斥", ""),
    "English farming is changing quickly, for the better": ("英格兰农业正在快速改变，且是向好的方向", ""),
    "A golden decade for British vets is coming to an end": ("英国兽医的黄金十年即将终结", ""),
    "Britain's dairy farmers are pouring milk away": ("英国奶农正在倒掉牛奶", ""),
    "What Sir Keir Starmer gets wrong about deregulation": ("基尔·斯塔默爵士对放松监管的误解", ""),
    "The Bank of England's eyes and ears": ("英格兰银行的耳目", ""),
    "Britain's diplomatic footprint is diminishing": ("英国的外交版图正在缩小", ""),
    "Britain's foreign aid morphs from open-handed to hard-headed": ("英国对外援助从慷慨大方转向务实强硬", ""),
    "ByteDance is swallowing the internet—in China and beyond": ("字节跳动正在吞噬互联网——在中国内外皆然", ""),
    "Will the EU's new merger rules unleash a wave of dealmaking?": ("欧盟新并购规则将掀起并购浪潮吗？", ""),
    "A new case of chip smuggling shows the limits of export controls": ("一起新的芯片走私案揭示出口管制的局限", ""),
    "Welcome to emoji school": ("欢迎来到表情符号学校", ""),
    "The war's biggest corporate winners and losers may surprise you": ("战争中最大的企业赢家和输家可能会让你大吃一惊", ""),
    "How much will America's oilmen benefit from the Iran war?": ("美国石油人从伊朗战争中能获益多少？", ""),
    "Big food's troubles go from bad to worse": ("大型食品企业的麻烦雪上加霜", ""),
    "Meta and Google face a reckoning over social-media addiction": ("Meta和谷歌面临社交媒体成瘾问题的清算", ""),
    "Amazon's unprecedented gamble on AI redemption might just work": ("亚马逊在AI救赎上的史无前例赌注或许会奏效", ""),
    "How high could global inflation go?": ("全球通胀能攀升到多高？", ""),
    "Even the best-case scenario for energy markets is disastrous": ("即便是能源市场最乐观的情景也是灾难性的", ""),
    "China's new masterplan for its tech economy in 2030 and beyond": ("中国2030年及以后科技经济的新总体规划", ""),
    "Christine Lagarde's sober tone on the Gulf war energy shock": ("克里斯蒂娜·拉加德对海湾战争能源冲击的冷静基调", ""),
    "Westerners are fleeing their countries in record numbers": ("西方人正以创纪录的数量离开本国", ""),
    "Markets are gripped by an alarming cognitive dissonance": ("市场陷入令人担忧的认知失调", ""),
    "The decline and fall of the Roman currency empire": ("罗马货币帝国的衰落与覆灭", ""),
    "China is winning the AI talent race": ("中国正赢得AI人才争夺战", ""),
    "NASA's Moon-base plans mark a rethinking of its future": ("NASA的月球基地计划标志着对其未来的重新思考", ""),
    "Autonomous swarms are the future of drone warfare": ("自主蜂群是无人机战争的未来", ""),
    "Is playing music good for the brain?": ("演奏音乐对大脑有益吗？", ""),
    "Everyone knows divorce is costly. But children pay most dearly": ("众所周知离婚代价高昂，但孩子付出的代价最为沉重", ""),
    "The forgotten man who pre-dated Mussolini and Hitler": ("那个被遗忘的、早于墨索里尼和希特勒的人", ""),
    "What is the big deal with Ovid and artists?": ("奥维德与艺术家之间有何深厚渊源？", ""),
    'With "SNL UK", Britain\'s laughing stock appreciates': ('随着"SNL UK"的出现，英国笑料股值上涨', ""),
    "Russia should not be welcome at the world's top art show": ("俄罗斯不应受邀参加世界顶级艺术展", ""),
    "Young people all over the world are clicking with mahjong": ("全球年轻人正在爱上麻将", ""),
    "Chuck Norris made onions cry": ("查克·诺里斯让洋葱哭泣", ""),
}

NY_0413 = {**COMMON,
    "New Directors, New Films": ("新导演，新电影", ""),
    "Pick Three: Spring Fabulosity": ("精选三则：春日风情", ""),
    "On and Off the Avenue: Spring in the Trenches": ("街头街尾：战壕里的春天", ""),
    "Donald Trump and Pete Hegseth's Warped Vision of the Iran War (Comment)": ("特朗普与赫格塞斯对伊朗战争的扭曲愿景", "评论"),
    "Geese, Cooked (Winging It)": ("鹅，熟了", "即兴随想"),
    "Happy Hour with Emanuel Ax (Old Friends)": ("与埃曼纽尔·阿克斯的欢乐时光", "故人"),
    "Getting Older with Clare Barron and Anne Kauffman (The Boards)": ("与克莱尔·巴伦和安妮·考夫曼共话老去", "舞台"),
    "Do the Circulation-Desk Shuffle (In the Stacks)": ("在流通台前的舞步", "书架之间"),
    "Why Are People Injecting Themselves with Peptides? (Brave New World Dept.)": ("人们为何给自己注射肽？", "美丽新世界"),
    "Can Sponge Cities Save Us from the Coming Floods? (The Control of Nature)": ("海绵城市能让我们免受洪灾吗？", "驯服自然"),
    "Sam Altman May Control Our Future—Can He Be Trusted? (A Reporter at Large)": ("萨姆·奥特曼或许掌控着我们的未来——他可信吗？", "深度报道"),
    "How the Internet Fringe Infiltrated Republican Politics (The Political Scene)": ("互联网边缘群体如何渗透共和党政治", "政治现场"),
    "Our Mom-and-Pop Data Center": ("我们的夫妻档数据中心", ""),
    "Rate Your Happiness": ("给你的幸福打分", "小说"),
    "We Are All Constantly Mutating—and That's a Good Thing (Books)": ("我们都在不断变异——这是件好事", "书评"),
    "Briefly Noted (Books)": ("简短书评", ""),
    "Will Biblical Womanhood Box You In or Set You Free? (Books)": ("圣经中的女性气质会束缚还是解放你？", "书评"),
    "In Marie NDiaye's Spellbinding New Novel, Witchcraft Stays in the Family (Books)": ("在玛丽·恩迪亚耶迷人的新小说中，巫术世代相传", "书评"),
    "The New Museum Returns, but Humans Are Left Behind (The Art World)": ("新美术馆归来，人类却被抛在身后", "艺术界"),
    "Kanye West Makes a Record for the A.I. Era (Pop Music)": ("坎耶·韦斯特为AI时代制作唱片", "流行音乐"),
    "Broadway's \"Dog Day Afternoon\" Is a Dog (The Theatre)": ("百老汇版《炎热的下午》是条狗", "剧评"),
    "Savannah Guthrie's Excruciating Story, on \"Today\" (On Television)": ("萨凡娜·古斯里在《今日》节目上的痛苦故事", "电视评论"),
    "An Artists' Duel Proves Restorative in \"The Christophers\" (The Current Cinema)": ("艺术家之决斗在《克里斯托弗斯》中令人振奋", "影评"),
    "Theodore Roosevelt Taylor": ("西奥多·罗斯福·泰勒", "诗歌"),
    "Meanwhile It Rains for Two Weeks and the Heat Never Breaks": ("与此同时雨下了两周，酷热未曾消散", "诗歌"),
    "The Crossword: Monday, April 6, 2026": ("填字游戏：2026年4月6日（周一）", ""),
}

NY_0406 = {**COMMON,
    "Marie Antoinette-Era Fashion Plates": ("玛丽·安托瓦内特时代的时尚版画", ""),
    "China's Shifting Relationship to the Countryside": ("中国与农村地区关系的演变", ""),
    "What Was Behind the T.S.A. Meltdown?": ("美国运输安全管理局崩溃背后是什么？", ""),
    "Trump's War Hits the Chaiwalas": ("特朗普的战争波及街头茶摊小贩", ""),
    "Stephanie Hsu Does the Time Warp": ("许玮伦穿越时空", ""),
    "Signed, Sealed, Delivered—and Afloat": ("签署、盖印、交付——并漂浮于水上", ""),
    "Reality-TV Deconstructor": ("真人秀解构者", ""),
    "How I Became a Filmmaker": ("我如何成为一名电影人", ""),
    "The Camps Promising to Turn You—or Your Son—Into an Alpha Male": ("那些承诺将你或你儿子打造成阿尔法男性的营地", ""),
    "He Helped Stop Iran from Getting the Bomb": ("他帮助阻止了伊朗获得核弹", ""),
    "At Synagogues, Tensions Are Boiling Over": ("犹太会堂内，紧张局势一触即发", ""),
    "If I Made Novelty T-Shirts": ("如果我做搞笑T恤", ""),
    "Enough for Now": ("目前已经足够", "小说"),
    "How to Measure the Good Life": ("如何衡量美好生活", ""),
    "The Ample Rewards of Ben Lerner's Slender New Novel": ("本·勒纳轻薄新小说的丰厚回报", ""),
    "Briefly Noted": ("简短书评", ""),
    "Kia Damon's Audacious Florida Cooking": ("基亚·达蒙大胆的佛罗里达烹饪", ""),
    '"Jury Duty Presents: Company Retreat" and the Age of the Prestige Prank Show': ("《陪审员义务：公司静修》与精品恶作剧节目时代", ""),
    "The Unseen Work of One of Iran's Greatest Filmmakers": ("伊朗最伟大电影人之一的不为人知之作", ""),
    "The Great-Grandmothers": ("曾祖母们", "诗歌"),
    "Following Bashō's Narrow Walk Into the Interior": ("追随芭蕉踏上奥之细道", "诗歌"),
    "The Crossword: Monday, March 30, 2026": ("填字游戏：2026年3月30日（周一）", ""),
}

NY_0330 = {**COMMON,
    "Elaine Reichek's Needlepoint Revolution": ("伊莱恩·赖谢克的刺绣革命", ""),
    "Patricia Cornwell on Crime and Creativity": ("帕特里夏·康薇尔谈犯罪与创作", ""),
    "The First Casualty of Trump's War in Iran Was the Truth": ("特朗普伊朗战争的第一个牺牲品是真相", ""),
    "Whose Line Is It Anyway?": ("这到底是谁的台词？", ""),
    "Between Sting and the Deep Blue Sea": ("斯汀与深蓝大海之间", ""),
    "Steve Zahn's Father-Daughter Dance": ("史蒂夫·扎恩的父女之舞", ""),
    "Remembering Calvin Tomkins, a Master of the Profile": ("缅怀人物特写大师卡尔文·汤普金斯", ""),
    "Robyn, on Her Own": ("罗宾，独自前行", ""),
    "Does A.I. Need a Constitution?": ("AI需要一部宪法吗？", ""),
    "Is Cuba Next?": ("古巴会是下一个吗？", ""),
    "The Last Generation": ("最后一代", ""),
    "Schools to Root for After Your Bracket Fails": ("当你的淘汰赛预测失败后，值得支持的学校", ""),
    "Floating": ("漂浮", "小说"),
    "N.Y.C. Spring Bingo": ("纽约市春日宾果", ""),
    "Under the Influence at the Whitney Biennial": ("在惠特尼双年展上心醉神迷", ""),
    "How Bad Is Plagiarism, Really?": ("剽窃到底有多严重？", ""),
    "Engels in the Outfield": ("外野的恩格斯", ""),
    "Briefly Noted": ("简短书评", ""),
    "A \"Baritenor\" Soars in \"Tristan und Isolde\"": ("一位"次高男高音"在《特里斯坦与伊索尔德》中大放异彩", ""),
    '"DTF St. Louis" Peers Into the Suburban Male Psyche': ("《DTF圣路易斯》窥探郊区男性心理", ""),
    "Coots": ("白骨顶鸟", "诗歌"),
    'Midnight in the Pain-Relief Aisle of CVS Thinking About "The Cloud of Unknowing"': ('在CVS药店止痛药货架前的午夜，思考《不知之云》', "诗歌"),
    "The Crossword: Wednesday, March 18, 2026": ("填字游戏：2026年3月18日（周三）", ""),
}

ALL = {
    'data/economist/2026-04-04.json': ECONOMIST_0404,
    'data/economist/2026-03-28.json': ECONOMIST_0328,
    'data/new_yorker/2026-04-13.json': NY_0413,
    'data/new_yorker/2026-04-06.json': NY_0406,
    'data/new_yorker/2026-03-30.json': NY_0330,
}

for path, translations in ALL.items():
    with open(path, encoding='utf-8') as f:
        issue = json.load(f)
    matched = total = 0
    for section in issue['toc']:
        for article in section['articles']:
            total += 1
            key = normalize(article['title'])
            if key in translations:
                article['title_zh'] = translations[key][0]
                article['subtitle_zh'] = translations[key][1] or article.get('subtitle', '')
                matched += 1
            else:
                article['title_zh'] = article['title']
                article['subtitle_zh'] = article.get('subtitle', '')
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(issue, f, ensure_ascii=False, indent=2)
    print(f'{path}: {matched}/{total} translated')
